### ISSUE TITLE
Changing component states can make the containing application's behavior unpredictable.

### ISSUE THREAD

**Issue by mradzinski** [myinnos/AppIconNameChanger#1] opened 2017-02-24 23:40 UTC
This library might work as a nice POC, but be careful if you happen to use it in production, setting `DONT_KILL_APP` and changing component states can make the containing application's behavior extremely unpredictable.

**Comment by myinnos** [comment] 2017-02-27 10:55
Thank you for your valuable feedback!
can you provide any `Source` for  **application will behavior extremely unpredictable.**
I will update in [README](https://github.com/myinnos/AppIconNameChanger/blob/master/README.md)

**Comment by myinnos** [comment] 2017-03-06 12:07
Sorry @mradzinski, I'm closing the issue because I have not received any answer from you in 1 week. If you still experience the issue feel free to reopen it and give me more info to try to reproduce the error.

**Closed as completed by myinnos** 2017-03-06 12:07 UTC
Labels: help wanted
